move ctrf to push, always generate report

diff --git a/.github/workflows/ci-push.yml b/.github/workflows/ci-push.yml
--- a/.github/workflows/ci-push.yml
+++ b/.github/workflows/ci-push.yml
@@ -26,6 +26,16 @@ jobs:
     - name: Install dependencies
       run: npm ci
 
+    - name: Run npm audit
+      run: npm audit --json > audit-results.json
+
+    - name: Upload npm audit results
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: audit-results
+        path: audit-results.json
+
     - name: Cache Docker layers
       uses: actions/cache@v2
       with:
@@ -41,10 +51,30 @@ jobs:
       run: docker run --rm pd-test-task-devops npm run lint > lint-results.txt
 
     - name: Run tests in Docker container
+      id: run_tests
       env:
         API_TOKEN: ${{ secrets.API_TOKEN }}
       run: |
         docker run --rm -e API_TOKEN=$API_TOKEN -v $PWD/test-results:/usr/src/app/test-results pd-test-task-devops bash -c "npm test -- --json --outputFile=/usr/src/app/test-results/test-results.json && chmod -R 755 /usr/src/app/test-results && node jest-to-ctrf.js"
+      continue-on-error: true
+
+    - name: Publish CTRF Test Summary Results
+      run: npx github-actions-ctrf summary ctrf-results/ctrf-results.json
+      if: always()
+  
+    - name: Publish CTRF Detailed Test Summary Results
+      run: npx github-actions-ctrf tests ctrf-results/ctrf-results.json
+      if: always()
+  
+    - name: Publish CTRF Failed Test Summary Results
+      run: npx github-actions-ctrf failed ctrf-results/ctrf-results.json
+      if: always()
+
+    - name: Fail the workflow if tests failed
+      if: steps.run_tests.outcome == 'failure'
+      run: |
+        echo "Tests failed, look at the summary and fix them :)"
+        exit 1
 
     - name: Fetch base branch for comparison
       run: git fetch origin ${{ github.ref }} --depth=1000
